### ISSUE TITLE
generating list from Risk.csv  bulletin_script.py

### ISSUE THREAD

**Issue by luisrodriguezgalvez** [acapet/ForCoast-SM-A2#13]
(tested in Windows)
In reader = csv.reader(f, delimiter='\t'), line 54, delimiter='\t' does not find tabs in Risk.csv and 2. the blank in-between rows are deleted (manually) from Risk.csv.

With no manual modifications to Risk.csv, the variable risktab, looks like:
[['2021-11-10T00:00:00.000000000\t0.0'], [], ['2021-11-10T12:00:00.000000000\t0.0'], [], ['2021-11-11T00:00:00.000000000\t0.0'], [], ['2021-11-11T12:00:00.000000000\t0.0'], [], ['2021-11-12T00:00:00.000000000\t0.0'], [], ['2021-11-12T12:00:00.000000000\t0.0'], [], ['2021-11-13T00:00:00.000000000\t0.0'], [], ['2021-11-13T12:00:00.000000000\t0.0'], [], ['2021-11-14T00:00:00.000000000\t0.0']]

When it should look like:
[['2021-11-10T00:00:00.0000000000', '0.0'], ['2021-11-10T12:00:00.000000000', '0.0'], ['2021-11-11T00:00:00.000000000', '0.0'], ['2021-11-11T12:00:00.000000000', '0.0'], ['2021-11-12T00:00:00.000000000', '0.0'], ['2021-11-12T12:00:00.000000000', '0.0'], ['2021-11-13T00:00:00.000000000', '0.0'], ['2021-11-13T12:00:00.000000000', '0.0'], ['2021-11-14T00:00:00.000000000', '0.0']]

**Comment by acapet** [comment]
Have a look at 676d6bfad9f6e213f2b3dc014412d6dba6b6867a .
I've changed '\t' for ',' , when writing and reading the .csv. 

I passes in Linux, could you test it in Windows and close this issue if it goes fine ?

**Comment by luisrodriguezgalvez** [comment]
(In Windows)
That fixes the issue with the delimiter.

The problem with the blank rows in Risk.csv in between remains. For that, I committed 3e12fde63a628cc360cbc44411aaa94117f19e96.

Can you check if that works in your end? If so, we can close the issue.

**Comment by luisrodriguezgalvez** [comment]
This push should fix it 23e94bb71a8c2335f6a8bb96bf32ba4546249660, the previous one was wrong.
