### ISSUE TITLE
TODO include in run_py.sh, when running bulletin_script, a way to identify -T input (release date)

### ISSUE THREAD

**Issue by luisrodriguezgalvez** [acapet/ForCoast-SM-A2#14]
So the bulletin overwrites the default release date present in config.yaml. The change to accept that input is made in bulletin_script.py, it is only needed in run_py.sh to include it in the complete workflow.

**Comment by luisrodriguezgalvez** [comment]
This also holds for other input like target and source coordinates.

**Comment by acapet** [comment]
I don't see any reason 'release date' should be in the config.yaml
You can access it in run_py.sh using the `date` bash command.

There certainly is also a python command to get current date.
Release date and current date (date of execution) are the same thing, right ?

**Comment by luisrodriguezgalvez** [comment]
As long as the workflow (pre, processing, post, bulletin) is called as a whole then is OK since all the parameters are passed to the run_py.sh.
Since I believe that will be the case, it is OK. I close the issue.

"Release date and current date (date of execution) are the same thing, right ?"
If the service usage is as intended, as a 'constant watch' triggered daily, then that is the case.
