### ISSUE TITLE
Kernel Issue

### ISSUE THREAD

**Issue by acapet** [acapet/ForCoast-SM-A2#4]
Something the line X below (forcoast.py):

```
# RUN SIMULATION    
output_file = pset.ParticleFile(name=options['out_filename'], outputdt=delta(minutes=options['savedt']))
t0=time.time()
if options['through_surface']:
  pset.execute(kernels, runtime=delta(days=options['simlength']), dt=delta(minutes=options['dt']), output_file=output_file, recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle1, ErrorCode.ErrorThroughSurface: DeleteParticle2})
else:
X  pset.execute(kernels, runtime=delta(days=options['simlength']), dt=delta(minutes=options['dt']), output_file=output_file, recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle,  ErrorCode.ErrorThroughSurface: DeleteParticle})  
              # verbose_progress=False)**
t1=time.time() ; totaltime=t1-t0 ; print("computing time :",totaltime)
output_file.close()
```

throws the error : 

using  3  nested grids
using just currents, no Stokes drift
Using horizontal diffusion
Freezing beached particles
INFO: Compiled ForCoastParticleAdvectionRK4_3DDiffusionUniformKhFrozenbeachckernel_dikessave_positiondecay ==> /tmp/parcels-1000/f7d6cd65002daff29fadb64223847236_0.so
Traceback (most recent call last):
  File "forcoast.py", line 253, in <module>
    pset.execute(kernels, runtime=delta(days=options['simlength']), dt=delta(minutes=options['dt']), output_file=output_file, recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle,  ErrorCode.ErrorThroughSurface: DeleteParticle})  
  File "/home/arthur/miniconda3/envs/forcoastA2/lib/python3.6/site-packages/parcels/particleset.py", line 673, in execute
    self.kernel.load_lib()
  File "/home/arthur/miniconda3/envs/forcoastA2/lib/python3.6/site-packages/parcels/kernel.py", line 231, in load_lib
    self._lib = npct.load_library(self.lib_file, '.')
  File "/home/arthur/miniconda3/envs/forcoastA2/lib/python3.6/site-packages/numpy/ctypeslib.py", line 150, in load_library
    return ctypes.cdll[libpath]
  File "/home/arthur/miniconda3/envs/forcoastA2/lib/python3.6/ctypes/\_\_init\_\_.py", line 423, in \_\_getitem\_\_
    return getattr(self, name)
  File "/home/arthur/miniconda3/envs/forcoastA2/lib/python3.6/ctypes/\_\_init\_\_.py", line 418, in \_\_getattr\_\_
    dll = self._dlltype(name)
  File "/home/arthur/miniconda3/envs/forcoastA2/lib/python3.6/ctypes/\_\_init\_\_.py", line 348, in \_\_init\_\_
    self._handle = _dlopen(self._name, mode)
OSError: /tmp/parcels-1000/f7d6cd65002daff29fadb64223847236_0.so: undefined symbol: func
Exception ignored in: <bound method ParticleFile.\_\_del\_\_ of <parcels.particlefile.ParticleFile object at 0x7fa1ad34bc50>>
Traceback (most recent call last):
  File "/home/arthur/miniconda3/envs/forcoastA2/lib/python3.6/site-packages/parcels/particlefile.py", line 189, in \_\_del\_\_
  File "/home/arthur/miniconda3/envs/forcoastA2/lib/python3.6/site-packages/parcels/particlefile.py", line 194, in close
  File "/home/arthur/miniconda3/envs/forcoastA2/lib/python3.6/site-packages/parcels/particlefile.py", line 306, in export
  File "/home/arthur/miniconda3/envs/forcoastA2/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
NameError: name 'open' is not defined

**Comment by acapet** [comment]
There are those different Error Handling functions : DeleteParticle1 , DeleteParticle2 , DeleteParticle..

Are all of them valid ?

**Comment by acapet** [comment]
OK, just for info, if it may help..

I thought this may be related to something solved in the more recent Parcels version. 
So, I've modified environment.yml to update parcel:2.3.0

But, doing so, I get the following error instead. So .. Well .. Not sure that's the way to go, finally. 

(forcoastA2) arthur@arthur-ThinkPad-P15-Gen-1:~/Desktop/DOCS/PROJECTS/FORECOAST/Pilot/SM/ForCoast-SM-A3$ ./run_py.sh eforie 2020-06-20 10 [28.6803,44.2201] [28.6611,44.0535,28.6617,44.0553]
mkdir: cannot create directory ‘/home/arthur/Desktop/DOCS/PROJECTS/FORECOAST/Pilot/SM/ForCoast-SM-A3/testdata/’: File exists
python forcoast.py -y eforie -T 2020-06-20 -p 10 -s [28.6803,44.2201] -t [28.6611,44.0535,28.6617,44.0553] -d /home/arthur/Desktop/DOCS/PROJECTS/FORECOAST/Pilot/SM/ForCoast-SM-A3/testdata/ 
running in 3D
Replace selected input with input from command line
Pollutant release coordinates: x0=[28.6803], y0=[44.2201]
Target area coordinates: targetx=[28.6611, 28.6617], targety=[44.0535, 44.0553]
Start date: 2020-06-20
Simulation length: 10
Data directory: /home/arthur/Desktop/DOCS/PROJECTS/FORECOAST/Pilot/SM/ForCoast-SM-A3/testdata/
PHY PATH: /home/arthur/Desktop/DOCS/PROJECTS/FORECOAST/Pilot/SM/ForCoast-SM-A3/testdata/2_EFORIE_1h_*_grid_W_*.nc*
WFILES:  ['/home/arthur/Desktop/DOCS/PROJECTS/FORECOAST/Pilot/SM/ForCoast-SM-A3/testdata/2_EFORIE_1h_20200601_20200630_grid_W_20200619-20200619.nc', '/home/arthur/Desktop/DOCS/PROJECTS/FORECOAST/Pilot/SM/ForCoast-SM-A3/testdata/2_EFORIE_1h_20200601_20200630_grid_W_20200620-20200620.nc', '/home/arthur/Desktop/DOCS/PROJECTS/FORECOAST/Pilot/SM/ForCoast-SM-A3/testdata/2_EFORIE_1h_20200601_20200630_grid_W_20200621-20200621.nc', '/home/arthur/Desktop/DOCS/PROJECTS/FORECOAST/Pilot/SM/ForCoast-SM-A3/testdata/2_EFORIE_1h_20200601_20200630_grid_W_20200622-20200622.nc', '/home/arthur/Desktop/DOCS/PROJECTS/FORECOAST/Pilot/SM/ForCoast-SM-A3/testdata/2_EFORIE_1h_20200601_20200630_grid_W_20200623-20200623.nc', '/home/arthur/Desktop/DOCS/PROJECTS/FORECOAST/Pilot/SM/ForCoast-SM-A3/testdata/2_EFORIE_1h_20200601_20200630_grid_W_20200624-20200624.nc', '/home/arthur/Desktop/DOCS/PROJECTS/FORECOAST/Pilot/SM/ForCoast-SM-A3/testdata/2_EFORIE_1h_20200601_20200630_grid_W_20200625-20200625.nc', '/home/arthur/Desktop/DOCS/PROJECTS/FORECOAST/Pilot/SM/ForCoast-SM-A3/testdata/2_EFORIE_1h_20200601_20200630_grid_W_20200626-20200626.nc', '/home/arthur/Desktop/DOCS/PROJECTS/FORECOAST/Pilot/SM/ForCoast-SM-A3/testdata/2_EFORIE_1h_20200601_20200630_grid_W_20200627-20200627.nc', '/home/arthur/Desktop/DOCS/PROJECTS/FORECOAST/Pilot/SM/ForCoast-SM-A3/testdata/2_EFORIE_1h_20200601_20200630_grid_W_20200628-20200628.nc', '/home/arthur/Desktop/DOCS/PROJECTS/FORECOAST/Pilot/SM/ForCoast-SM-A3/testdata/2_EFORIE_1h_20200601_20200630_grid_W_20200629-20200629.nc', '/home/arthur/Desktop/DOCS/PROJECTS/FORECOAST/Pilot/SM/ForCoast-SM-A3/testdata/2_EFORIE_1h_20200601_20200630_grid_W_20200630-20200630.nc']
Traceback (most recent call last):
  File "forcoast.py", line 113, in <module>
    myfieldset.append(get_nemo_fields(ufiles,vfiles,wfiles,mesh_mask,run3D=options['run3D'],indices=indices,chunksize=False,vdiffusion=options['vdiffusion'],beaching=options['beaching']))
  **File "/home/arthur/Desktop/DOCS/PROJECTS/FORECOAST/Pilot/SM/ForCoast-SM-A3/Processing/forcoast_loaders.py", line 46, in get_nemo_fields
    fieldset=FieldSet.from_nemo(filenames, variables, dimensions, indices=indices, field_chunksize=cs)**
  File "/home/arthur/miniconda3/envs/forcoastA2/lib/python3.6/site-packages/parcels/fieldset.py", line 489, in from_nemo
    chunksize=chunksize, gridindexingtype='nemo', **kwargs)
  File "/home/arthur/miniconda3/envs/forcoastA2/lib/python3.6/site-packages/parcels/fieldset.py", line 604, in from_c_grid_dataset
    chunksize=chunksize, gridindexingtype=gridindexingtype, **kwargs)
  File "/home/arthur/miniconda3/envs/forcoastA2/lib/python3.6/site-packages/parcels/fieldset.py", line 412, in from_netcdf
    fieldtype=fieldtype, chunksize=varchunksize, dataFiles=dFiles, **kwargs)
  File "/home/arthur/miniconda3/envs/forcoastA2/lib/python3.6/site-packages/parcels/field.py", line 454, in from_netcdf
    allow_time_extrapolation=allow_time_extrapolation, interp_method=interp_method, **kwargs)
  File "/home/arthur/miniconda3/envs/forcoastA2/lib/python3.6/site-packages/parcels/field.py", line 207, in __init__
    raise SyntaxError('Field received an unexpected keyword argument "%s"' % list(kwargs.keys())[0])
**SyntaxError: Field received an unexpected keyword argument "field_chunksize"**

**Comment by lucvandenbulcke** [comment]
This is linked to a bug in parcels 2.2.0 and 2.2.1, which I corrected manually in my parcels code (but obviously not in the parcels repository version 2.2.X). The correction was brought in the parcels repository in 2.3.0
I now updated some files in the "docker" branch to use parcels 2.3.0
